package com.dungeon.engine

class SimulationController {

    companion object {
        init {
            // Loads the shared library generated by CMakeLists.txt
            System.loadLibrary("engine")
        }
    }

    // Native method declaration bridging to jni_bridge.cpp
    external fun nativeRunSimulation(start: Long, end: Long)

    fun executeTick(startTime: Long, endTime: Long) {
        // Invokes the headless C++ logic
        nativeRunSimulation(startTime, endTime)
    }
}
